package com.example.meditime.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
/**
 * DTO representing the response from an AI analysis.
 *
 * Contains identified patterns, associated risks, and recommendations
 * generated by the AI system.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class AiAnalysisResponse {
    private String patterns;
    private String risks;
    private String recommendations;
}