// Amy Wickham 12178502
package com.example.meditime.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * Entity class representing a Medication in the system.
 * Contains basic medication details such as name, description,
 * side effects, and interaction information.
 */
@Entity
@Getter
@Setter
public class Medication {

    /**
     * Primary key for Medication entity.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long medicationId;

    /**
     * Name of the medication.
     * Cannot be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Description of the medication.
     */
    private String description;

    /**
     * Side effects associated with the medication.
     */
    private String sideEffects;

    /**
     * Information about possible interactions with other medications.
     */
    private String interactionInfo;
}
