// Amy Wickham 121785021
package com.example.meditime.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * Entity representing a potential interaction between two medications.
 * Stores the interaction details and its severity level.
 */
@Entity
@Getter
@Setter
public class MedicationInteraction {

    /**
     * Primary key for the MedicationInteraction entity.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long interactionId;

    /**
     * First medication involved in the interaction.
     */
    @ManyToOne
    @JoinColumn(name = "medication_id_1")
    private Medication medication1;

    /**
     * Second medication involved in the interaction.
     */
    @ManyToOne
    @JoinColumn(name = "medication_id_2")
    private Medication medication2;

    /**
     * Description of the nature of the interaction between the two medications.
     */
    private String interactionDescription;

    /**
     * Severity level of the interaction, classified using an enumerated type.
     */
    @Enumerated(EnumType.STRING)
    private Severity severity;

    /**
     * Enumeration representing the possible severity levels for a medication interaction.
     */
    public enum Severity {
        LOW, MEDIUM, HIGH, CRITICAL
    }
}
