// Amy Wickham 12178502
// File: Role.java
// Description: Represents a user role in the MediTime system (e.g., Admin, Carer, Manager).

package com.example.meditime.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter // Lombok automatically generates getters for all fields
@Setter // Lombok automatically generates setters for all fields
public class Role {

    // Primary key for the Role entity, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long roleId;

    // Role name must be unique (e.g., "ADMIN", "CARER")
    @Column(unique = true)
    private String roleName;

    // No manual getters and setters needed due to Lombok annotations
}
