package com.example.medicationapp.model.repository

import com.example.medicationapp.model.Client
import com.example.medicationapp.model.dao.ClientDao

class ClientRepository(private val clientDao: ClientDao) {

    /** Inserts a new client and returns its autogenerated ID */
    suspend fun insertClient(client: Client): Long =
        clientDao.insertClient(client)

    /** Returns all clients */
    suspend fun getAllClients(): List<Client> =
        clientDao.getAllClients()

    /** Returns a single client by its ID (or null if not found) */
    suspend fun getClientById(clientId: Long): Client? =
        clientDao.getClientById(clientId)

    /** Returns all clients assigned to a given carer */
    suspend fun getClientsByCarerId(carerId: Long): List<Client> =
        clientDao.getClientsByCarerId(carerId)

    /** Deletes the given client */
    suspend fun deleteClient(client: Client) =
        clientDao.deleteClient(client)
}
